package me.surrett.gsd;

import org.apache.logging.log4j.LogManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private static final String GREETING = "Hello world.";
	
    public String getGreeting() {
        return GREETING;
    }

    public static void main(final String[] args) {
        LogManager.getLogger(App.class).info(new App().getGreeting());
    }
}
