package me.surrett.gsd;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private static final Logger LOGGER = LogManager.getLogger(App.class);
	private static final String GREETING = "Hello world.";
	
    public String getGreeting() {
    	return GREETING;
    }

    public static void main(final String[] args) {
    	LOGGER.info(new App().getGreeting());
    }
}
